on:
  workflow_call:
    inputs:
      extra-args:
        type: string
        default: ""

jobs:
  build-ziggurat:
    runs-on: ubuntu-latest
    env:
      EXTRA_ARGS: ${{ inputs.features }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - name: Compile unit tests
        run: cargo test --all-targets --no-run $EXTRA_ARGS
      - uses: actions/upload-artifact@v3
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat*
